[network]
port=1927
serverip=192.168.123.8
autostart=1
aplication=TesApp.exe
aplication2=AOPRSimClient
;
nafsserver=..\NAFS\
nafsbridge=..\NAFS\
nsfsserver=..\NSFS\
nsfsbridge=..\NSFS\
nssfsserver=..\NSSFS\
nssfsbridge=..\NSSFS\

;IP Instruktur yg mau dinyalakan
instNafs = 192.168.123.8
instNsfs = 192.168.1.1
instNssfs = 192.168.1.1

;
clientmode = NAFS
