[network]
port=1927
serverip=192.168.123.8
autostart=1

[application]
clientapp=FiringSystemInst.exe
nafsserverapp=SystemServerNafs.exe
nafsbridgeapp=BridgeNafs.exe
nsfsserverapp=SystemServerNsfs.exe
nsfsbridgeapp=BridgeNsfs.exe
nssfsserverapp=SystemServerNssfs.exe
nssfsbridgeapp=BridgeNssfs.exe
sessionvoipapp=SessionVoip.exe

[url]
nafsserver=..\NAFS\
nafsbridge=..\NAFS\
nsfsserver=..\NSFS\
nsfsbridge=..\NSFS\
nssfsserver=..\NSSFS\
nssfsbridge=..\NSSFS\
sessionvoip=..\COMM\

;IP Instruktur yg mau dinyalakan
instNafs = 192.168.123.8
instNsfs = 192.168.1.1
instNssfs = 192.168.1.1

[instruktur world]
clientmode = NAFS

[ip console]
instruktur nsfs = 10.10.10.10
mk3 2h nsfs = 10.10.10.11
mk4 nsfs = 10.10.10.12
c802 = 10.10.10.14
tds = 10.10.10.15
c705 = 10.10.10.16
yakhont = 10.10.10.17
57mm digital = 10.10.10.18
mr 35 = 10.10.10.19
57mm manual = 10.10.10.20
mm 103 = 10.10.10.21
3d nsfs = 10.10.10.254	

instruktur nafs = 10.10.20.10
mk3 2h nafs = 10.10.20.11
mk4 nafs = 10.10.20.12
ciws 730 = 10.10.20.14
eo tracker 730 = 10.10.20.15
ak 230 = 10.10.20.16
mr 203 = 10.10.20.17
3d nafs = 10.10.20.254

instruktur nssfs = 10.10.30.10
mk3 2h nssfs = 10.10.30.11
sps =  10.10.30.12
mk4 nssfs = 10.10.30.13
sut black shark = 10.10.30.15
rbu digital = 10.10.30.16
rbu manual = 10.10.30.17
3d nssfs = 10.10.30.254								